language: node_js
node_js: node
script:
- npm run test:lint
- polymer test --skip-plugin local
addons:
  jwt:
    secure: Bbii9Xv9R7d8pQ20zZEll9rLQs6gAAJLaFNznJnL1gLbRwzfjYdAkUfYBbFOD9TxJoDO4fGy6+LY+OXmiNZFnmsfIQBKrDm7uoc7ALJt6nkcB/lwEn/g6gApfpAEb5ITz72JY2FOc9dljx4xBO6wmiBDgp/qsYyjRXaG5W/oCxvtwzHmeQT+y+A6CMu3l5mf/7oSjggetdWNqGAEh6EY/45GwTE70cXHwPFjNPaVFcJ8kbuSCEhkLOZcoePSEfUqgVJBlhT8YgW4sSvYMI9lLw9tDe0IX7A2PLn+1bPmMNNfq7NCGxAGa3yxX/NhNmAJU4EnpTb9kF9IGtZUSqTJbmEU02Mg9hmHpgX6+nOT4W9ufnJqk8u5miBJ+bFlBGqDIZMb1mzaApMd9rF5yqI8ww3otgTAIYH9GKHqAWRsyhM011UzsoJnaNL5GPB93uXMds5EHaHv8Xs05W8PQ9ZTOjH+VVaN7Yt3Pl5cacORfV2vVi5poN3nFXnUYVUY8rF4B7nxk6QriChGESIuQItKQGV3NQYzU15JvSuoO7q41AecM3GauGRyIrySkgXcSGNXBqZ4+hmHS5QAaj+KlHeCW7Npr123ZVDnwX/BAvn5Ho55RQ7ZV9N/YskiOgYztxBvvg3NZyz2uN9Rl2xwf+8pCEuCyX6Oa8mYvUO5NS3LVLs=
env:
  global:
    SAUCE_USERNAME: Desire2Learn
