language: node_js
node_js: node
script:
- npm run test:lint
- polymer test --skip-plugin local
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  # SAUCE_ACCESS_KEY
  - secure: U7aE3alJQawTIgR9NtNjkhQIwV7Bkol9zrj3A/IZysjD8/fuX7wBdGXE5lWUlrv6+qKgKM6aw7F6X4rTVJcHQ98hSEf0VoA2Pv8yvY4StMiU3IeMblfNJkCB9XqFMQMkPu7Uq6z5y9M0jVytK1/rPrwKGZKxQHj/NBb9zWL8IjDtXNeYhlspy38HpvZ1HKIzzZN384/9dYfhZj2UNbucBMYQ99PgL7Ajn8J+U5uTkxWNSKvCDVT73DEX6NpJfSZ4Dj0VpraXrqfUouyHO8VcbELs2m3HZq9VJPLonByjeq1jOXO9BOU0+Q6LytM1x4xaZQswTA2VrWI62+w/1dQp1M3susqLriexFycqR6KjXAor0j1BopUXLDF0fJW/xdZpAcn11QEbqqoCkhLsHHG/iaPVZuhg2q1gvJS5ePJUxrl6QeKI3k+QtOZ110cDGZVlGa3TWSqyUz9kgEnqhPp3mhi5lpyPj0w0ima9ncgfj/MAgWxIE29klqC/IV4jeyrTcczh9LU0asfK+yCFv+o3Z+Xymxd51tIOAkQ8N4CWY0jnfFsOFBE4SjUfLo8wFkONQJ+nbnMOtD+aBM3YZpWhwySK21YED+7L002ulIzwiUO9KfDSCiJec3mcETXqmXi1KOLz9XmoeU4ajeGxSSraMlmfeOxGqvMUaq6WrWAu9t8=
